language: android

jdk:
  - oraclejdk8

android:
    components:
        - tools
        - tools #update to latest, cannot control version
        - platform-tools #latest
        - build-tools-24.0.1
        - android-24
        - extra
        - extra-android-m2repository
        - extra-google-google_play_services

notifications:
  email: false

#cache between builds
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

script:
    - ./gradlew lintFroyoRelease  assembleFroyoRelease
    - ./gradlew lintLatestRelease assembleLatestRelease
    - ./gradlew test
