language: android

android:
    components:
        - tools-25.1.17
        - build-tools-23.0.3
        - android-22
        - extras
        - extra-android-m2repository
        - extra-google-google_play_services

script:
    - ./gradlew assembleFroyoRelease
    - ./gradlew assembleLatestRelease
    - ./gradlew test
