language: android

android:
    components:
        - tools #standard travis version
        - tools #update to latest, cannot control version
        - platform-tools #latest
        - build-tools #latest
        - android-22
        - extra
        - extra-android-m2repository
        - extra-google-google_play_services

notifications:
  email: false

#cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

script:
    - ./gradlew lintFroyoRelease
    - ./gradlew lintLatestRelease
    - ./gradlew test
