language: android

android:
    components:
        - build-tools
        - android-22
        - extras
        - extra-android-m2repository
        - extra-google-google_play_services

script:
    - ./gradlew assembleFroyoRelease
    - ./gradlew assembleLatestRelease
    - ./gradlew test
